### ISSUE TITLE
Documentation v4

### ISSUE THREAD

**Issue by kestarumper** [vazco/uniforms#1305]
~Blocked by #1306~

Implemented by #1384

## Outline

1. Overview
    1. Introduction
    2. Motivation
    3. Comparison matrix
    4. CLI
2. Getting started
    1. Installation
    2. Basic usage (rename?)
    3. Choosing the schema
3. Examples
Każdy przykład będzie napisany w:
Theme: **AntD**
Bridge: **Zod, JSON Schema, Simpl-Schema**
    1. Custom field #1132
    2. Validation
        1. Sync validation
        2. Async validation
    3. Multi-step form
4. Advanced usage
    1. Custom AutoField (createAutoField)
    2. Custom theme
5. API Reference
    1. `useField`
    2. `useForm`
    3. `<AutoForm />`
    4. `<AutoField />`
6. Guides
    1. Migration v3 to v4
    2. Migration v2 to v3

## TODO
- [x] Overview (Introduction, Motivation, Comparison matrix)
- [x] Getting started
- [ ] Examples
  - [x] #1386
  - [ ] Custom field @zendranm 
  - [ ] Validation
  - [ ] Multi-step form
- [ ] Advanced usage
  - [ ] Custom AutoField (createAutoField) @kestarumper 
  - [ ] Custom theme
- [ ] API Reference @zaxovaiko 

### Must have
- [X] Delete "Getting started > advanced usage"
- [X] Delete "Top Bar > Tutorial"
- [X] Link "Playground" to examples
- [ ] Migration v3 to v4 - is outdated, needs to be fully checked
- [x] FAQ - copy and delete "can I use react 18"
- [X] Tutorials > Custom Field - will go to examples
- [x] Tutorials > Custom Theme - will go to examples
- [X] API Reference - copy and delete outdated
- [ ] Ensure Algolia works - update Algolia search
